language: node_js
os: osx
osx_image: xcode7.3
node_js:
  - "4"
  - "6"
  - "7"
install:
  - npm install
  - npm install -g gulp
  - xcodebuild -version
  - xcrun simctl list
script:
  - _FORCE_LOGS=1 gulp once
after_success:
  - gulp coveralls
