os: osx
osx_image: xcode7.3
language: node_js
node_js:
  - "7"
  - "6"
  - "4"
install:
  - node --version
  - npm install
  - npm install -g gulp
script:
  - _FORCE_LOGS=1 gulp once
after_success:
  - gulp coveralls
